apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: annuaire-app
spec:
  replicas: 1
  selector:
    app: annuaire-app
  template:
    metadata:
      labels:
        app: annuaire-app
    spec:
      containers:
        - name: annuaire-app
          image: annuaire-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/annuaire"
---
apiVersion: v1
kind: Service
metadata:
  name: annuaire-service
spec:
  selector:
    app: annuaire-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
