apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: annuaire-db
spec:
  replicas: 1
  selector:
    app: annuaire-db
  template:
    metadata:
      labels:
        app: annuaire-db
    spec:
      containers:
        - name: annuaire-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "annuaire"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: annuaire-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
